### ISSUE TITLE
Doesn't build with cl 19.00.24213.1

### ISSUE THREAD

**Issue by nico** [sgraham/tim#1]
C:\src\tim>m
tim.cc
c:\src\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\win_sdk\bin\..\..\VC\include\limits(2
10): error C2220: warning treated as error - no 'object' file generated
c:\src\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\win_sdk\bin\..\..\VC\include\limits(2
10): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guarantee
d. Specify /EHsc
c:\src\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\win_sdk\bin\..\..\VC\include\limits(2
10): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which
you used to build without warnings
        1 file(s) copied.
